"""Change in video model

Revision ID: 8c1954c48e4b
Revises: f8ffe5e6210c
Create Date: 2026-08-10 23:31:59.004561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c1954c48e4b'
down_revision: Union[str, Sequence[str], None] = 'f8ffe5e6210c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('car_brands_name_key'), 'car_brands', type_='unique')
    op.drop_constraint(op.f('car_brands_slug_key'), 'car_brands', type_='unique')
    op.create_index(op.f('ix_car_brands_name'), 'car_brands', ['name'], unique=True)
    op.create_index(op.f('ix_car_brands_slug'), 'car_brands', ['slug'], unique=True)
    op.add_column('car_models', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('car_models_slug_key'), 'car_models', type_='unique')
    op.create_index(op.f('ix_car_models_brand_id'), 'car_models', ['brand_id'], unique=False)
    op.create_index(op.f('ix_car_models_is_active'), 'car_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_car_models_is_deleted'), 'car_models', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_car_models_is_featured'), 'car_models', ['is_featured'], unique=False)
    op.create_index(op.f('ix_car_models_slug'), 'car_models', ['slug'], unique=True)
    op.create_index(op.f('ix_car_models_year'), 'car_models', ['year'], unique=False)
    op.create_foreign_key(None, 'car_models', 'car_brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_column('car_models', 'brand_name')
    op.add_column('car_variants', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('car_variants', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_car_variants_car_model_id'), 'car_variants', ['car_model_id'], unique=False)
    op.create_index(op.f('ix_car_variants_is_deleted'), 'car_variants', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'car_variants', 'car_models', ['car_model_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('videos', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'car_variants', type_='foreignkey')
    op.drop_index(op.f('ix_car_variants_is_deleted'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_car_model_id'), table_name='car_variants')
    op.drop_column('car_variants', 'is_deleted')
    op.drop_column('car_variants', 'updated_at')
    op.add_column('car_models', sa.Column('brand_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'car_models', type_='foreignkey')
    op.drop_index(op.f('ix_car_models_year'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_slug'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_is_featured'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_is_deleted'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_is_active'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_brand_id'), table_name='car_models')
    op.create_unique_constraint(op.f('car_models_slug_key'), 'car_models', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('car_models', 'is_deleted')
    op.drop_index(op.f('ix_car_brands_slug'), table_name='car_brands')
    op.drop_index(op.f('ix_car_brands_name'), table_name='car_brands')
    op.create_unique_constraint(op.f('car_brands_slug_key'), 'car_brands', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('car_brands_name_key'), 'car_brands', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
